[package]
name = "image-sorter"
version = "0.1.0"
authors = ["Shootertrex"]
edition = "2018"

[dependencies]
iced = { version = "0.2", features = ["image","async-std"] }
iced_native = "0.3" 
sorter_backend = { path = "../image_backend" }